// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package order

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"example/internal/query"

    "example/internal/repositories"

    "example/internal/models"
)

type last struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	conditionOpts []ConditionOption
}

// Last 获取最后一条记录（主键降序）
func (o *Order) Last() *last {
	return &last{
		core:          o,
		unscoped:      o.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (l *last) Tx(tx *query.Query) *last {
	l.tx = tx
	l.qTx = nil
	return l
}

// QueryTx 设置为手动事务
func (l *last) QueryTx(tx *query.QueryTx) *last {
	l.qTx = tx
	l.tx = nil
	return l
}

func (l *last) Select(field ...field.Expr) *last {
	l.selects = append(l.selects, field...)
	return l
}

func (l *last) ForUpdate() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *last) ForUpdateSkipLocked() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *last) ForUpdateNoWait() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *last) ForShare() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *last) ForShareSkipLocked() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *last) ForShareNoWait() *last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *last) Unscoped() *last {
	l.unscoped = true
	return l
}

func (l *last) Relation(opts ...RelationOption) *last {
	l.relationOpts = append(l.relationOpts, opts...)
	return l
}

func (l *last) Where(opts ...ConditionOption) *last {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

// Do 执行获取最后一条记录（主键降序）
func (l *last) Do(ctx context.Context) (*models.Order, error) {
	lq := l.core.q.Order
	if l.tx != nil {
		lq = l.tx.Order
	}
	if l.qTx != nil {
		lq = l.qTx.Order
	}
	lr := lq.WithContext(ctx)
	if l.core.newTableName != nil && *l.core.newTableName != "" {
		lr = lq.Table(*l.core.newTableName).WithContext(ctx)
	}
	if len(l.selects) > 0 {
		if l.core.newTableName == nil {
			lr = lr.Select(l.selects...)
		} else {
			fs := make([]field.Expr, 0, len(l.selects))
			for _, v := range l.selects {
				fs = append(fs, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
			lr = lr.Select(fs...)
		}
	}
	if l.unscoped {
		lr = lr.Unscoped()
	}
	if (l.tx != nil || l.qTx != nil) && l.lock != nil {
		lr = lr.Clauses(l.lock)
	}
	errFields := make([]zap.Field, 0)
	if len(l.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(l.conditionOpts))
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
		if len(conditions) > 0 {
			errFields = append(errFields, zap.Any("conditions", conditions))
			lr = lr.Where(conditions...)
		}
	}
	if len(l.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(l.relationOpts))
		for _, opt := range l.relationOpts {
			relations = append(relations, opt(l.core))
		}
		if len(relations) > 0 {
			errFields = append(errFields, zap.Any("relations", relations))
			lr = lr.Preload(relations...)
		}
	}
	res, err := lr.Last()
	if err != nil {
		if repositories.IsRealErr(err) {
			errFields = append(errFields, zap.Error(err))
			l.core.logger.Error("【Order.Last】失败", errFields...)
		}
		return nil, err
	}
	return res, nil
}
