// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package order

import (
	"context"

    "github.com/gorm-gen/plugin/paginate"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"example/internal/query"

    "example/internal/repositories"

    "example/internal/models"
)

type list struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	page          int
	pageSize      int
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	orderOpts     []OrderOption
	conditionOpts []ConditionOption
}

// List 获取数据列表
func (o *Order) List() *list {
	return &list{
		core:          o,
		unscoped:      o.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		orderOpts:     make([]OrderOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (l *list) Tx(tx *query.Query) *list {
	l.tx = tx
	if tx != nil {
		l.qTx = nil
	}
	return l
}

// QueryTx 设置为手动事务
func (l *list) QueryTx(tx *query.QueryTx) *list {
	l.qTx = tx
	if tx != nil {
		l.tx = nil
	}
	return l
}

func (l *list) Select(field ...field.Expr) *list {
	l.selects = append(l.selects, field...)
	return l
}

func (l *list) ForUpdate() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *list) ForUpdateSkipLocked() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *list) ForUpdateNoWait() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *list) ForShare() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *list) ForShareSkipLocked() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *list) ForShareNoWait() *list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *list) Unscoped() *list {
	l.unscoped = true
	return l
}

func (l *list) Relation(opts ...RelationOption) *list {
	l.relationOpts = append(l.relationOpts, opts...)
	return l
}

func (l *list) Order(opts ...OrderOption) *list {
	l.orderOpts = append(l.orderOpts, opts...)
	return l
}

func (l *list) Where(opts ...ConditionOption) *list {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

// Page 列表分页
func (l *list) Page(page, pageSize uint) *list {
	l.page = int(page)
	l.pageSize = int(pageSize)
	return l
}

// Do 执行获取数据列表
func (l *list) Do(ctx context.Context) ([]*models.Order, error) {
	lq := l.core.q.Order
	if l.tx != nil {
		lq = l.tx.Order
	}
	if l.qTx != nil {
		lq = l.qTx.Order
	}
	lr := lq.WithContext(ctx)
	if l.core.newTableName != nil && *l.core.newTableName != "" {
		lr = lq.Table(*l.core.newTableName).WithContext(ctx)
	}
	if len(l.selects) > 0 {
		if l.core.newTableName == nil {
			lr = lr.Select(l.selects...)
		} else {
			fs := make([]field.Expr, 0, len(l.selects))
			for _, v := range l.selects {
				fs = append(fs, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
			lr = lr.Select(fs...)
		}
	}
	if l.unscoped {
		lr = lr.Unscoped()
	}
	if (l.tx != nil || l.qTx != nil) && l.lock != nil {
		lr = lr.Clauses(l.lock)
	}
	if len(l.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(l.conditionOpts))
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
		if len(conditions) > 0 {
			lr = lr.Where(conditions...)
		}
	}
	if len(l.orderOpts) > 0 {
		orders := make([]field.Expr, 0, len(l.orderOpts))
		for _, opt := range l.orderOpts {
			orders = append(orders, opt(l.core))
		}
		if len(orders) > 0 {
			lr = lr.Order(orders...)
		}
	}
	if l.page > 0 && l.pageSize > 0 {
		lr = lr.Scopes(paginate.Gen(l.page, l.pageSize))
	}
	if len(l.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(l.relationOpts))
		for _, opt := range l.relationOpts {
			relations = append(relations, opt(l.core))
		}
		if len(relations) > 0 {
			lr = lr.Preload(relations...)
		}
	}
	list, err := lr.Find()
	if err != nil {
		if repositories.IsRealErr(err) {
			l.core.logger.Error("【Order.List】失败", zap.Error(err))
		}
		return nil, err
	}
	return list, nil
}
