// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package order

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"example/internal/query"

	"example/internal/repositories"

	"example/internal/models"
)

type _multiFirst struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	conditionOpts []ConditionOption
	sharding      []string
	worker        chan struct{}
}

// MultiFirst 获取多表随机第一条记录（主键升序）
func (o *Order) MultiFirst(sharding []string) *_multiFirst {
	return &_multiFirst{
		core:          o,
		unscoped:      o.unscoped,
		selects:       make([]field.Expr, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (f *_multiFirst) Worker(worker chan struct{}) *_multiFirst {
	if worker == nil {
		return f
	}
	f.worker = worker
	return f
}

// Tx 设置为事务
func (f *_multiFirst) Tx(tx *query.Query) *_multiFirst {
	f.tx = tx
	if tx != nil {
		f.qTx = nil
	}
	return f
}

// QueryTx 设置为手动事务
func (f *_multiFirst) QueryTx(tx *query.QueryTx) *_multiFirst {
	f.qTx = tx
	if tx != nil {
		f.tx = nil
	}
	return f
}

func (f *_multiFirst) Select(field ...field.Expr) *_multiFirst {
	f.selects = append(f.selects, field...)
	return f
}

func (f *_multiFirst) ForUpdate() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return f
}

func (f *_multiFirst) ForUpdateSkipLocked() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_multiFirst) ForUpdateNoWait() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_multiFirst) ForShare() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return f
}

func (f *_multiFirst) ForShareSkipLocked() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_multiFirst) ForShareNoWait() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_multiFirst) Unscoped() *_multiFirst {
	f.unscoped = true
	return f
}

func (f *_multiFirst) Where(opts ...ConditionOption) *_multiFirst {
	f.conditionOpts = append(f.conditionOpts, opts...)
	return f
}

// Do 执行获取多表随机第一条记录（主键升序）
func (f *_multiFirst) Do(ctx context.Context) (*models.Order, error) {
	if len(f.sharding) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	fq := f.core.q.Order
	if f.tx != nil {
		fq = f.tx.Order
	}
	if f.qTx != nil {
		fq = f.qTx.Order
	}
	var conditions []gen.Condition
	if len(f.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(f.conditionOpts))
		for _, opt := range f.conditionOpts {
			conditions = append(conditions, opt(f.core))
		}
	}
	var fieldExpr []field.Expr
	if len(f.selects) > 0 {
		fieldExpr = make([]field.Expr, 0, len(f.selects))
		if f.core.newTableName == nil {
			fieldExpr = append(fieldExpr, f.selects...)
		} else {
			for _, v := range f.selects {
				fieldExpr = append(fieldExpr, field.NewField(*f.core.newTableName, v.ColumnName().String()))
			}
		}
	}
	wg := sync.WaitGroup{}
	endChan := make(chan struct{})
	errChan := make(chan error)
	resultChan := make(chan *models.Order)
	for _, sharding := range f.sharding {
		f.worker <- struct{}{}
		wg.Add(1)
		go func(sharding string) {
			defer func() {
				if r := recover(); r != nil {
					f.core.logger.Error(fmt.Sprintf("【Order.MultiFirst.%s】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan <- fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				<-f.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, ConditionSharding(sharding)(f.core))
			fr := fq.WithContext(ctx)
			if len(fieldExpr) > 0 {
				fr = fr.Select(fieldExpr...)
			}
			if f.unscoped {
				fr = fr.Unscoped()
			}
			if (f.tx != nil || f.qTx != nil) && f.lock != nil {
				fr = fr.Clauses(f.lock)
			}
			res, err := fr.Where(_conditions...).First()
			if err != nil {
				if repositories.IsRealErr(err) {
					f.core.logger.Error(fmt.Sprintf("【Order.MultiFirst.%s】失败", sharding), zap.Error(err))
				}
				if !errors.Is(err, gorm.ErrRecordNotFound) {
					errChan <- err
				}
				return
			}
			resultChan <- res
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan <- struct{}{}
	}()
	select {
	case res := <-resultChan:
		return res, nil
	case <-endChan:
		return nil, gorm.ErrRecordNotFound
	case err := <-errChan:
		return nil, err
	}
}
