// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"

	"example/internal/query"

	"example/internal/repositories"
)

type _shardingDelete struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
	sharding      []string
	worker        chan struct{}
	scopes        []func(gen.Dao) gen.Dao
}

// ShardingDelete 删除分表数据
func (o *Order) ShardingDelete(sharding []string) *_shardingDelete {
	return &_shardingDelete{
		core:          o,
		unscoped:      true,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
		scopes:        make([]func(gen.Dao) gen.Dao, 0),
	}
}

func (d *_shardingDelete) Worker(worker chan struct{}) *_shardingDelete {
	if worker == nil {
		return d
	}
	d.worker = worker
	return d
}

// Tx 设置为事务
func (d *_shardingDelete) Tx(tx *query.Query) *_shardingDelete {
	d.tx = tx
	if tx != nil {
		d.qTx = nil
	}
	return d
}

// QueryTx 设置为手动事务
func (d *_shardingDelete) QueryTx(tx *query.QueryTx) *_shardingDelete {
	d.qTx = tx
	if tx != nil {
		d.tx = nil
	}
	return d
}

func (d *_shardingDelete) Unscoped(unscoped ...bool) *_shardingDelete {
	_unscoped := true
	if len(unscoped) > 0 {
		_unscoped = unscoped[0]
	}
	d.unscoped = _unscoped
	return d
}

func (d *_shardingDelete) Scopes(funcs ...func(gen.Dao) gen.Dao) *_shardingDelete {
	d.scopes = append(d.scopes, funcs...)
	return d
}

func (d *_shardingDelete) Where(opts ...ConditionOption) *_shardingDelete {
	d.conditionOpts = append(d.conditionOpts, opts...)
	return d
}

// Do 执行删除分表数据
func (d *_shardingDelete) Do(ctx context.Context) (int64, map[string]int64, error) {
	_lenSharding := len(d.sharding)
	if _lenSharding == 0 {
		return 0, nil, nil
	}
	qTx := d.qTx
	var innerTx *query.QueryTx
	var cancel context.CancelFunc
	if d.tx == nil && d.qTx == nil {
		innerTx = d.core.q.Begin()
		qTx = innerTx
		ctx, cancel = context.WithCancel(ctx)
		defer cancel()
	}
	_condLen := len(d.conditionOpts)
	sm := sync.Map{}
	wg := sync.WaitGroup{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range d.sharding {
		d.worker <- struct{}{}
		wg.Add(1)
		go func(sharding string) {
			defer func() {
				if r := recover(); r != nil {
					d.core.logger.Error(fmt.Sprintf("【Order.ShardingDelete.%s】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan <- fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				<-d.worker
			}()
			defer wg.Done()
			_conditionOpts := make([]ConditionOption, _condLen, _condLen+1)
			copy(_conditionOpts, d.conditionOpts)
			_conditionOpts = append(_conditionOpts, ConditionSharding(sharding))
			rows, err := d.core.Delete().
				Tx(d.tx).
				QueryTx(qTx).
				Unscoped(d.unscoped).
				Scopes(d.scopes...).
				Where(_conditionOpts...).
				Do(ctx)
			if err != nil {
				errChan <- err
				return
			}
			sm.Store(sharding, rows)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan <- struct{}{}
	}()
	select {
	case <-endChan:
		if innerTx != nil {
			if err := innerTx.Commit(); err != nil {
				if repositories.IsRealErr(err) {
					d.core.logger.Error("【Order.ShardingDelete.Commit】失败", zap.Error(err), zap.ByteString("debug.Stack", debug.Stack()))
				}
				return 0, nil, err
			}
		}
		rowsAffected := int64(0)
		m := make(map[string]int64, _lenSharding)
		sm.Range(func(key, value interface{}) bool {
			v := value.(int64)
			m[key.(string)] = v
			rowsAffected += v
			return true
		})
		return rowsAffected, m, nil
	case err := <-errChan:
		if innerTx != nil {
			cancel()
			_ = innerTx.Rollback()
		}
		return 0, nil, err
	}
}
