// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"example/internal/query"

	"example/internal/repositories"
)

type _shardingSum struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	genField      field.Expr
	conditionOpts []ConditionOption
	sharding      []string
	worker        chan struct{}
	writeDB       bool
	scopes        []func(gen.Dao) gen.Dao
}

// ShardingSum 分表SUM数据
func (o *Order) ShardingSum(genField field.Expr, sharding []string) *_shardingSum {
	return &_shardingSum{
		core:          o,
		unscoped:      o.unscoped,
		genField:      genField,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
		scopes:        make([]func(gen.Dao) gen.Dao, 0),
	}
}

func (s *_shardingSum) Worker(worker chan struct{}) *_shardingSum {
	if worker == nil {
		return s
	}
	s.worker = worker
	return s
}

// Tx 设置为事务
func (s *_shardingSum) Tx(tx *query.Query) *_shardingSum {
	s.tx = tx
	if tx != nil {
		s.qTx = nil
	}
	return s
}

// QueryTx 设置为手动事务
func (s *_shardingSum) QueryTx(tx *query.QueryTx) *_shardingSum {
	s.qTx = tx
	if tx != nil {
		s.tx = nil
	}
	return s
}

func (s *_shardingSum) Unscoped() *_shardingSum {
	s.unscoped = true
	return s
}

func (s *_shardingSum) Scopes(funcs ...func(gen.Dao) gen.Dao) *_shardingSum {
	s.scopes = append(s.scopes, funcs...)
	return s
}

func (s *_shardingSum) Where(opts ...ConditionOption) *_shardingSum {
	s.conditionOpts = append(s.conditionOpts, opts...)
	return s
}

func (s *_shardingSum) WriteDB() *_shardingSum {
	s.writeDB = true
	return s
}

// Do 执行分表SUM数据
func (s *_shardingSum) Do(ctx context.Context) (decimal.Decimal, map[string]decimal.Decimal, error) {
	_lenSharding := len(s.sharding)
	if _lenSharding == 0 {
		return decimal.Zero, nil, nil
	}
	sq := s.core.q.Order
	if s.tx != nil {
		sq = s.tx.Order
	}
	if s.qTx != nil {
		sq = s.qTx.Order
	}
	var conditions []gen.Condition
	if _len := len(s.conditionOpts); _len > 0 {
		conditions = make([]gen.Condition, 0, _len)
		for _, opt := range s.conditionOpts {
			conditions = append(conditions, opt(s.core))
		}
	}
	expr := field.NewField("", s.genField.ColumnName().String()).Sum().As("sum")
	wg := sync.WaitGroup{}
	sm := sync.Map{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range s.sharding {
		s.worker <- struct{}{}
		wg.Add(1)
		go func(sharding string) {
			defer func() {
				if r := recover(); r != nil {
					s.core.logger.Error(fmt.Sprintf("【Order.ShardingSum.%s】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan <- fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				<-s.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, ConditionSharding(sharding)(s.core))
			sr := sq.WithContext(ctx).Select(expr)
			if s.writeDB {
				sr = sr.WriteDB()
			}
			if s.unscoped {
				sr = sr.Unscoped()
			}
			if len(s.scopes) > 0 {
				sr = sr.Scopes(s.scopes...)
			}
			var data Sum
			if err := sr.Where(_conditions...).Scan(&data); err != nil {
				if repositories.IsRealErr(err) {
					s.core.logger.Error(fmt.Sprintf("【Order.ShardingSum.%s】失败", sharding), zap.Error(err), zap.ByteString("debug.Stack", debug.Stack()))
				}
				errChan <- err
				return
			}
			sm.Store(sharding, data.Sum)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan <- struct{}{}
	}()
	select {
	case <-endChan:
		sum := decimal.Zero
		m := make(map[string]decimal.Decimal, _lenSharding)
		sm.Range(func(key, value interface{}) bool {
			v := value.(decimal.Decimal)
			m[key.(string)] = v
			sum = sum.Add(v)
			return true
		})
		return sum, m, nil
	case err := <-errChan:
		return decimal.Zero, nil, err
	}
}
