// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package order

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"example/internal/query"

	"example/internal/repositories"

	"example/internal/models"
)

type _shardingLast struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	conditionOpts []ConditionOption
	sharding      []string
	worker        chan struct{}
	writeDB       bool
	scopes        []func(gen.Dao) gen.Dao
}

// ShardingLast 获取分表中随机最后一条记录（主键降序）
func (o *Order) ShardingLast(sharding []string) *_shardingLast {
	return &_shardingLast{
		core:          o,
		unscoped:      o.unscoped,
		selects:       make([]field.Expr, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
		scopes:        make([]func(gen.Dao) gen.Dao, 0),
	}
}

func (l *_shardingLast) Worker(worker chan struct{}) *_shardingLast {
	if worker == nil {
		return l
	}
	l.worker = worker
	return l
}

// Tx 设置为事务
func (l *_shardingLast) Tx(tx *query.Query) *_shardingLast {
	l.tx = tx
	if tx != nil {
		l.qTx = nil
	}
	return l
}

// QueryTx 设置为手动事务
func (l *_shardingLast) QueryTx(tx *query.QueryTx) *_shardingLast {
	l.qTx = tx
	if tx != nil {
		l.tx = nil
	}
	return l
}

func (l *_shardingLast) Select(field ...field.Expr) *_shardingLast {
	l.selects = append(l.selects, field...)
	return l
}

func (l *_shardingLast) ForUpdate() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *_shardingLast) ForUpdateSkipLocked() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_shardingLast) ForUpdateNoWait() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_shardingLast) ForShare() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *_shardingLast) ForShareSkipLocked() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_shardingLast) ForShareNoWait() *_shardingLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_shardingLast) Unscoped() *_shardingLast {
	l.unscoped = true
	return l
}

func (l *_shardingLast) Scopes(funcs ...func(gen.Dao) gen.Dao) *_shardingLast {
	l.scopes = append(l.scopes, funcs...)
	return l
}

func (l *_shardingLast) Where(opts ...ConditionOption) *_shardingLast {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

func (l *_shardingLast) WriteDB() *_shardingLast {
	l.writeDB = true
	return l
}

// Do 执行获取分表中随机最后一条记录（主键降序）
func (l *_shardingLast) Do(ctx context.Context) (*models.Order, error) {
	if len(l.sharding) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	lq := l.core.q.Order
	if l.tx != nil {
		lq = l.tx.Order
	}
	if l.qTx != nil {
		lq = l.qTx.Order
	}
	var conditions []gen.Condition
	if _len := len(l.conditionOpts); _len > 0 {
		conditions = make([]gen.Condition, 0, _len)
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
	}
	var fieldExpr []field.Expr
	if _len := len(l.selects); _len > 0 {
		fieldExpr = make([]field.Expr, 0, _len)
		if l.core.newTableName == nil {
			fieldExpr = append(fieldExpr, l.selects...)
		} else {
			for _, v := range l.selects {
				fieldExpr = append(fieldExpr, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
		}
	}
	wg := sync.WaitGroup{}
	endChan := make(chan struct{})
	errChan := make(chan error)
	resultChan := make(chan *models.Order)
	for _, sharding := range l.sharding {
		l.worker <- struct{}{}
		wg.Add(1)
		go func(sharding string) {
			defer func() {
				if r := recover(); r != nil {
					l.core.logger.Error(fmt.Sprintf("【Order.ShardingLast.%s】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan <- fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				<-l.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, ConditionSharding(sharding)(l.core))
			lr := lq.WithContext(ctx)
			if len(fieldExpr) > 0 {
				lr = lr.Select(fieldExpr...)
			}
			if l.writeDB {
				lr = lr.WriteDB()
			}
			if l.unscoped {
				lr = lr.Unscoped()
			}
			if len(l.scopes) > 0 {
				lr = lr.Scopes(l.scopes...)
			}
			if (l.tx != nil || l.qTx != nil) && l.lock != nil {
				lr = lr.Clauses(l.lock)
			}
			res, err := lr.Where(_conditions...).Last()
			if err != nil {
				if repositories.IsRealErr(err) {
					l.core.logger.Error(fmt.Sprintf("【Order.ShardingLast.%s】失败", sharding), zap.Error(err), zap.ByteString("debug.Stack", debug.Stack()))
				}
				if !errors.Is(err, gorm.ErrRecordNotFound) {
					errChan <- err
				}
				return
			}
			resultChan <- res
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan <- struct{}{}
	}()
	select {
	case res := <-resultChan:
		return res, nil
	case <-endChan:
		return nil, gorm.ErrRecordNotFound
	case err := <-errChan:
		return nil, err
	}
}
