// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package order

import (
	"context"
	"runtime/debug"

	"github.com/opentracing/opentracing-go"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"example/internal/query"

	"example/internal/repositories"
)

type _sum struct {
	core          *Order
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	genField      field.Expr
	conditionOpts []ConditionOption
	writeDB       bool
	scopes        []func(gen.Dao) gen.Dao
	trace         bool
}

// Sum SUM数据
func (o *Order) Sum(genField field.Expr) *_sum {
	return &_sum{
		core:          o,
		unscoped:      o.unscoped,
		genField:      genField,
		conditionOpts: make([]ConditionOption, 0),
		scopes:        make([]func(gen.Dao) gen.Dao, 0),
	}
}

// Tx 设置为事务
func (s *_sum) Tx(tx *query.Query) *_sum {
	s.tx = tx
	if tx != nil {
		s.qTx = nil
	}
	return s
}

// QueryTx 设置为手动事务
func (s *_sum) QueryTx(tx *query.QueryTx) *_sum {
	s.qTx = tx
	if tx != nil {
		s.tx = nil
	}
	return s
}

func (s *_sum) Unscoped(unscoped ...bool) *_sum {
	_unscoped := true
	if len(unscoped) > 0 {
		_unscoped = unscoped[0]
	}
	s.unscoped = _unscoped
	return s
}

func (s *_sum) Scopes(funcs ...func(gen.Dao) gen.Dao) *_sum {
	s.scopes = append(s.scopes, funcs...)
	return s
}

func (s *_sum) WriteDB() *_sum {
	s.writeDB = true
	return s
}

func (s *_sum) Trace() *_sum {
	s.trace = true
	return s
}

func (s *_sum) Where(opts ...ConditionOption) *_sum {
	s.conditionOpts = append(s.conditionOpts, opts...)
	return s
}

type Sum struct {
    Sum decimal.Decimal `json:"sum"`
}

// Do 执行SUM数据
func (s *_sum) Do(ctx context.Context) (decimal.Decimal, error) {
	if s.trace {
		if parent := opentracing.SpanFromContext(ctx); parent != nil {
			if tracer := opentracing.GlobalTracer(); tracer != nil {
				span := tracer.StartSpan("SQL:Order.Sum", opentracing.ChildOf(parent.Context()))
				defer span.Finish()
			}
		}
	}
	sq := s.core.q.Order
	if s.tx != nil {
		sq = s.tx.Order
	}
	if s.qTx != nil {
		sq = s.qTx.Order
	}
	expr := field.NewField("", s.genField.ColumnName().String()).Sum().As("sum")
	sr := sq.WithContext(ctx)
	if s.core.newTableName != nil && *s.core.newTableName != "" {
		sr = sq.Table(*s.core.newTableName).WithContext(ctx)
	}
	sr = sr.Select(expr)
	if s.writeDB {
		sr = sr.WriteDB()
	}
	if s.unscoped {
		sr = sr.Unscoped()
	}
	if len(s.scopes) > 0 {
		sr = sr.Scopes(s.scopes...)
	}
	if _len := len(s.conditionOpts); _len > 0 {
		conditions := make([]gen.Condition, 0, _len)
		for _, opt := range s.conditionOpts {
			conditions = append(conditions, opt(s.core))
		}
		if len(conditions) > 0 {
			sr = sr.Where(conditions...)
		}
	}
	var data Sum
	if err := sr.Scan(&data); err != nil {
		if repositories.IsRealErr(err) {
			s.core.logger.Error("【Order.Sum】失败", zap.Error(err), zap.ByteString("debug.Stack", debug.Stack()))
		}
		return decimal.Zero, err
	}
	return data.Sum, nil
}
