// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameOrder = "order"

// Order 订单表
type Order struct {
	ID        int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录ID" json:"id"`                                // 记录ID
	Sharding  string                `gorm:"column:sharding;not null;comment:分表关键字段[月份:202503]" json:"sharding"`                            // 分表关键字段[月份:202503]
	UID       int                   `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                                                   // 用户ID
	OrderNo   string                `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                                          // 订单号
	Status    int8                  `gorm:"column:status;not null;comment:订单状态" json:"status"`                                             // 订单状态
	Amount    decimal.Decimal       `gorm:"column:amount;not null;default:0.00;comment:订单金额[单位:元]" json:"amount"`                          // 订单金额[单位:元]
	CreatedAt time.Time             `gorm:"column:created_at;not null;comment:创建日期" json:"created_at,omitzero" time_format:"sql_datetime"` // 创建日期
	UpdatedAt time.Time             `gorm:"column:updated_at;not null;comment:更新日期" json:"updated_at,omitzero" time_format:"sql_datetime"` // 更新日期
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间戳[0:未删除,非0:删除时间戳]" json:"-"`                             // 删除时间戳[0:未删除,非0:删除时间戳]
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
