// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID           int                   `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                                                          // 用户ID
	Name         string                `gorm:"column:name;not null;comment:姓名" json:"name"`                                                                             // 姓名
	CompanyID    int                   `gorm:"column:company_id;not null;comment:公司ID" json:"company_id"`                                                               // 公司ID
	Balance      decimal.Decimal       `gorm:"column:balance;not null;default:0.00;comment:钱包余额" json:"balance"`                                                        // 钱包余额
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建日期" json:"created_at,omitzero" time_format:"sql_datetime"` // 创建日期
	UpdatedAt    time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新日期" json:"updated_at,omitzero" time_format:"sql_datetime"` // 更新日期
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间戳[0:未删除,非0:删除时间戳]" json:"-"`                                                       // 删除时间戳[0:未删除,非0:删除时间戳]
	Company      *Company              `gorm:"foreignKey:CompanyID;references:ID" json:"company,omitempty"`
	IdentityCard *IdentityCard         `gorm:"foreignKey:UserID;references:ID" json:"identity_card,omitempty"`
	CreditCards  []*CreditCard         `gorm:"foreignKey:UserID;references:ID" json:"credit_cards,omitempty"`
	Languages    []Language            `gorm:"foreignKey:ID;joinForeignKey:UserID;joinReferences:LanguageID;many2many:user_language;references:ID" json:"languages,omitempty"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
