// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package language

import (
	"strings"
	"time"

	f "github.com/gorm-gen/field"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"

	"example/internal/global"

	"example/internal/query"

	"example/internal/repositories"
)

// Language 仓库/Repository
type Language struct {
	q            *query.Query
	db           *gorm.DB
	logger       *zap.Logger
	newTableName *string
}

// Option Language仓库初始化选项
type Option func(*Language)

func WithQuery(q *query.Query) Option {
	return func(l *Language) {
		l.q = q
	}
}

func WithLogger(logger *zap.Logger) Option {
	return func(l *Language) {
		l.logger = logger
	}
}

func WithDB(db *gorm.DB) Option {
	return func(l *Language) {
		l.db = db
	}
}

func WithNewTableName(newTableName string) Option {
	return func(l *Language) {
		l.newTableName = &newTableName
	}
}

// New Language仓库初始化
func New(opts ...Option) *Language {
	l := &Language{
		q:      repositories.GetQuery(),
		db:     global.DB,
		logger: global.Logger,
	}
	for _, opt := range opts {
		opt(l)
	}
	return l
}

// ConditionOption 字段条件筛选选项
type ConditionOption func(*Language) gen.Condition

// Condition 自定义字段条件筛选
func Condition(condition gen.Condition) ConditionOption {
	return func(*Language) gen.Condition {
		return condition
	}
}

func ConditionID(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		length := len(v)
		if l.newTableName != nil {
			if length == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Eq(0)
			}
			if length == 1 {
				return l.q.Language.Table(*l.newTableName).ID.Eq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).ID.In(v...)
		}
		if length == 0 {
			return l.q.Language.ID.Eq(0)
		}
		if length == 1 {
			return l.q.Language.ID.Eq(v[0])
		}
		return l.q.Language.ID.In(v...)
	}
}

func ConditionIDNot(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		length := len(v)
		if l.newTableName != nil {
			if length == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Neq(0)
			}
			if length == 1 {
				return l.q.Language.Table(*l.newTableName).ID.Neq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).ID.NotIn(v...)
		}
		if length == 0 {
			return l.q.Language.ID.Neq(0)
		}
		if length == 1 {
			return l.q.Language.ID.Neq(v[0])
		}
		return l.q.Language.ID.NotIn(v...)
	}
}

func ConditionIDGt(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Gt(0)
			}
			return l.q.Language.Table(*l.newTableName).ID.Gt(v[0])
		}
		if len(v) == 0 {
			return l.q.Language.ID.Gt(0)
		}
		return l.q.Language.ID.Gt(v[0])
	}
}

func ConditionIDGte(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Gte(0)
			}
			return l.q.Language.Table(*l.newTableName).ID.Gte(v[0])
		}
		if len(v) == 0 {
			return l.q.Language.ID.Gte(0)
		}
		return l.q.Language.ID.Gte(v[0])
	}
}

func ConditionIDLt(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Lt(0)
			}
			return l.q.Language.Table(*l.newTableName).ID.Lt(v[0])
		}
		if len(v) == 0 {
			return l.q.Language.ID.Lt(0)
		}
		return l.q.Language.ID.Lt(v[0])
	}
}

func ConditionIDLte(v ...int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) == 0 {
				return l.q.Language.Table(*l.newTableName).ID.Lte(0)
			}
			return l.q.Language.Table(*l.newTableName).ID.Lte(v[0])
		}
		if len(v) == 0 {
			return l.q.Language.ID.Lte(0)
		}
		return l.q.Language.ID.Lte(v[0])
	}
}

func ConditionIDBetween(left, right int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).ID.Between(left, right)
		}
		return l.q.Language.ID.Between(left, right)
	}
}

func ConditionIDNotBetween(left, right int) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).ID.NotBetween(left, right)
		}
		return l.q.Language.ID.NotBetween(left, right)
	}
}

func ConditionName(v ...string) ConditionOption {
	return func(l *Language) gen.Condition {
		length := len(v)
		if l.newTableName != nil {
			if length == 0 {
				return l.q.Language.Table(*l.newTableName).Name.Eq("")
			}
			return l.q.Language.Table(*l.newTableName).Name.Eq(v[0])
		}
		if length == 0 {
			return l.q.Language.Name.Eq("")
		}
		return l.q.Language.Name.Eq(v[0])
	}
}

func ConditionNameNeq(v ...string) ConditionOption {
	return func(l *Language) gen.Condition {
		length := len(v)
		if l.newTableName != nil {
			if length == 0 {
				return l.q.Language.Table(*l.newTableName).Name.Neq("")
			}
			return l.q.Language.Table(*l.newTableName).Name.Neq(v[0])
		}
		if length == 0 {
			return l.q.Language.Name.Neq("")
		}
		return l.q.Language.Name.Neq(v[0])
	}
}

func ConditionNameLike(v string) ConditionOption {
	return func(l *Language) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).Name.Like(v)
		}
		return l.q.Language.Name.Like(v)
	}
}

func ConditionNameNotLike(v string) ConditionOption {
	return func(l *Language) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).Name.NotLike(v)
		}
		return l.q.Language.Name.NotLike(v)
	}
}

func ConditionCreatedAt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Eq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Eq(v[0])
		}
		return l.q.Language.CreatedAt.Eq(time.Now())
	}
}

func ConditionCreatedAtNeq(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Neq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Neq(v[0])
		}
		return l.q.Language.CreatedAt.Neq(time.Now())
	}
}

func ConditionCreatedAtGt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Gt(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Gt(v[0])
		}
		return l.q.Language.CreatedAt.Gt(time.Now())
	}
}

func ConditionCreatedAtGte(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Gte(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Gte(v[0])
		}
		return l.q.Language.CreatedAt.Gte(time.Now())
	}
}

func ConditionCreatedAtLt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Lt(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Lt(v[0])
		}
		return l.q.Language.CreatedAt.Lt(time.Now())
	}
}

func ConditionCreatedAtLte(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).CreatedAt.Lte(v[0])
			}
			return l.q.Language.Table(*l.newTableName).CreatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.CreatedAt.Lte(v[0])
		}
		return l.q.Language.CreatedAt.Lte(time.Now())
	}
}

func ConditionCreatedAtBetween(left, right time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).CreatedAt.Between(left, right)
		}
		return l.q.Language.CreatedAt.Between(left, right)
	}
}

func ConditionCreatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).CreatedAt.NotBetween(left, right)
		}
		return l.q.Language.CreatedAt.NotBetween(left, right)
	}
}

func ConditionUpdatedAt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Eq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Eq(v[0])
		}
		return l.q.Language.UpdatedAt.Eq(time.Now())
	}
}

func ConditionUpdatedAtNeq(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Neq(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Neq(v[0])
		}
		return l.q.Language.UpdatedAt.Neq(time.Now())
	}
}

func ConditionUpdatedAtGt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Gt(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Gt(v[0])
		}
		return l.q.Language.UpdatedAt.Gt(time.Now())
	}
}

func ConditionUpdatedAtGte(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Gte(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Gte(v[0])
		}
		return l.q.Language.UpdatedAt.Gte(time.Now())
	}
}

func ConditionUpdatedAtLt(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Lt(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Lt(v[0])
		}
		return l.q.Language.UpdatedAt.Lt(time.Now())
	}
}

func ConditionUpdatedAtLte(v ...time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return l.q.Language.Table(*l.newTableName).UpdatedAt.Lte(v[0])
			}
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return l.q.Language.UpdatedAt.Lte(v[0])
		}
		return l.q.Language.UpdatedAt.Lte(time.Now())
	}
}

func ConditionUpdatedAtBetween(left, right time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Between(left, right)
		}
		return l.q.Language.UpdatedAt.Between(left, right)
	}
}

func ConditionUpdatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).UpdatedAt.NotBetween(left, right)
		}
		return l.q.Language.UpdatedAt.NotBetween(left, right)
	}
}

func ConditionDeletedAtIsZero() ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return f.NewDecimal(l.q.Language.DeletedAt, f.WithTableName(*l.newTableName)).Eq(decimal.Zero)
		}
		return f.NewDecimal(l.q.Language.DeletedAt).Eq(decimal.Zero)
	}
}

func ConditionDeletedAtGtZero() ConditionOption {
	return func(l *Language) gen.Condition {
		if l.newTableName != nil {
			return f.NewDecimal(l.q.Language.DeletedAt, f.WithTableName(*l.newTableName)).Gt(decimal.Zero)
		}
		return f.NewDecimal(l.q.Language.DeletedAt).Gt(decimal.Zero)
	}
}

// UpdateOption 数据更新选项
type UpdateOption func(*Language) field.AssignExpr

// Update 自定义数据更新
func Update(update field.AssignExpr) UpdateOption {
	return func(*Language) field.AssignExpr {
		return update
	}
}

func UpdateName(v string) UpdateOption {
	return func(l *Language) field.AssignExpr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).Name.Value(v)
		}
		return l.q.Language.Name.Value(v)
	}
}

func UpdateCreatedAt(v time.Time) UpdateOption {
	return func(l *Language) field.AssignExpr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).CreatedAt.Value(v)
		}
		return l.q.Language.CreatedAt.Value(v)
	}
}

func UpdateUpdatedAt(v time.Time) UpdateOption {
	return func(l *Language) field.AssignExpr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Value(v)
		}
		return l.q.Language.UpdatedAt.Value(v)
	}
}

// OrderOption 数据排序选项
type OrderOption func(*Language) field.Expr

// Order 自定义数据排序
func OrderBy(order field.Expr) OrderOption {
	return func(*Language) field.Expr {
		return order
	}
}

func OrderIDAsc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).ID.Asc()
		}
		return l.q.Language.ID.Asc()
	}
}

func OrderIDDesc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).ID.Desc()
		}
		return l.q.Language.ID.Desc()
	}
}

func OrderCreatedAtAsc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).CreatedAt.Asc()
		}
		return l.q.Language.CreatedAt.Asc()
	}
}

func OrderCreatedAtDesc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).CreatedAt.Desc()
		}
		return l.q.Language.CreatedAt.Desc()
	}
}

func OrderUpdatedAtAsc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Asc()
		}
		return l.q.Language.UpdatedAt.Asc()
	}
}

func OrderUpdatedAtDesc() OrderOption {
	return func(l *Language) field.Expr {
		if l.newTableName != nil {
			return l.q.Language.Table(*l.newTableName).UpdatedAt.Desc()
		}
		return l.q.Language.UpdatedAt.Desc()
	}
}

// RelationOption 关联模型预加载选项
type RelationOption func(*Language) field.RelationField

// Relation 自定义关联模型预加载
func Relation(relation field.RelationField) RelationOption {
	return func(*Language) field.RelationField {
		return relation
	}
}

func RelationAll() RelationOption {
	return func(*Language) field.RelationField {
		return field.Associations
	}
}
