// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package area

import (
	"strings"
	"time"

	f "github.com/gorm-gen/plugin/field"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"

	"example/internal/global"

	"example/internal/query"

	"example/internal/repositories"
)

// Area 仓库/Repository
type Area struct {
	q            *query.Query
	db           *gorm.DB
	logger       *zap.Logger
	unscoped     bool
	newTableName *string
}

// Option Area仓库初始化选项
type Option func(*Area)

func WithQuery(q *query.Query) Option {
	return func(a *Area) {
		a.q = q
	}
}

func WithLogger(logger *zap.Logger) Option {
	return func(a *Area) {
		a.logger = logger
	}
}

func WithDB(db *gorm.DB) Option {
	return func(a *Area) {
		a.db = db
	}
}

func WithNewTableName(newTableName string) Option {
	return func(a *Area) {
		a.newTableName = &newTableName
	}
}

func WithUnscoped() Option {
	return func(a *Area) {
		a.unscoped = true
	}
}

// New Area仓库初始化
func New(opts ...Option) *Area {
	a := &Area{
		q:      repositories.GetQuery(),
		db:     global.DB,
		logger: global.Logger,
	}
	for _, opt := range opts {
		opt(a)
	}
	return a
}

// ConditionOption 字段条件筛选选项
type ConditionOption func(*Area) gen.Condition

// Condition 自定义字段条件筛选
func Condition(condition gen.Condition) ConditionOption {
	return func(*Area) gen.Condition {
		return condition
	}
}

func ConditionID(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Eq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).ID.Eq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).ID.In(v...)
		}
		if length == 0 {
			return a.q.Area.ID.Eq(0)
		}
		if length == 1 {
			return a.q.Area.ID.Eq(v[0])
		}
		return a.q.Area.ID.In(v...)
	}
}

func ConditionIDNot(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Neq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).ID.Neq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).ID.NotIn(v...)
		}
		if length == 0 {
			return a.q.Area.ID.Neq(0)
		}
		if length == 1 {
			return a.q.Area.ID.Neq(v[0])
		}
		return a.q.Area.ID.NotIn(v...)
	}
}

func ConditionIDGt(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Gt(0)
			}
			return a.q.Area.Table(*a.newTableName).ID.Gt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.ID.Gt(0)
		}
		return a.q.Area.ID.Gt(v[0])
	}
}

func ConditionIDGte(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Gte(0)
			}
			return a.q.Area.Table(*a.newTableName).ID.Gte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.ID.Gte(0)
		}
		return a.q.Area.ID.Gte(v[0])
	}
}

func ConditionIDLt(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Lt(0)
			}
			return a.q.Area.Table(*a.newTableName).ID.Lt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.ID.Lt(0)
		}
		return a.q.Area.ID.Lt(v[0])
	}
}

func ConditionIDLte(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).ID.Lte(0)
			}
			return a.q.Area.Table(*a.newTableName).ID.Lte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.ID.Lte(0)
		}
		return a.q.Area.ID.Lte(v[0])
	}
}

func ConditionIDBetween(left, right int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).ID.Between(left, right)
		}
		return a.q.Area.ID.Between(left, right)
	}
}

func ConditionIDNotBetween(left, right int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).ID.NotBetween(left, right)
		}
		return a.q.Area.ID.NotBetween(left, right)
	}
}

func ConditionName(v ...string) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Name.Eq("")
			}
			return a.q.Area.Table(*a.newTableName).Name.Eq(v[0])
		}
		if length == 0 {
			return a.q.Area.Name.Eq("")
		}
		return a.q.Area.Name.Eq(v[0])
	}
}

func ConditionNameNeq(v ...string) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Name.Neq("")
			}
			return a.q.Area.Table(*a.newTableName).Name.Neq(v[0])
		}
		if length == 0 {
			return a.q.Area.Name.Neq("")
		}
		return a.q.Area.Name.Neq(v[0])
	}
}

func ConditionNameLike(v string) ConditionOption {
	return func(a *Area) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Name.Like(v)
		}
		return a.q.Area.Name.Like(v)
	}
}

func ConditionNameNotLike(v string) ConditionOption {
	return func(a *Area) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Name.NotLike(v)
		}
		return a.q.Area.Name.NotLike(v)
	}
}

func ConditionPid(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Eq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).Pid.Eq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).Pid.In(v...)
		}
		if length == 0 {
			return a.q.Area.Pid.Eq(0)
		}
		if length == 1 {
			return a.q.Area.Pid.Eq(v[0])
		}
		return a.q.Area.Pid.In(v...)
	}
}

func ConditionPidNot(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Neq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).Pid.Neq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).Pid.NotIn(v...)
		}
		if length == 0 {
			return a.q.Area.Pid.Neq(0)
		}
		if length == 1 {
			return a.q.Area.Pid.Neq(v[0])
		}
		return a.q.Area.Pid.NotIn(v...)
	}
}

func ConditionPidGt(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Gt(0)
			}
			return a.q.Area.Table(*a.newTableName).Pid.Gt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Pid.Gt(0)
		}
		return a.q.Area.Pid.Gt(v[0])
	}
}

func ConditionPidGte(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Gte(0)
			}
			return a.q.Area.Table(*a.newTableName).Pid.Gte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Pid.Gte(0)
		}
		return a.q.Area.Pid.Gte(v[0])
	}
}

func ConditionPidLt(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Lt(0)
			}
			return a.q.Area.Table(*a.newTableName).Pid.Lt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Pid.Lt(0)
		}
		return a.q.Area.Pid.Lt(v[0])
	}
}

func ConditionPidLte(v ...int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Pid.Lte(0)
			}
			return a.q.Area.Table(*a.newTableName).Pid.Lte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Pid.Lte(0)
		}
		return a.q.Area.Pid.Lte(v[0])
	}
}

func ConditionPidBetween(left, right int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Between(left, right)
		}
		return a.q.Area.Pid.Between(left, right)
	}
}

func ConditionPidNotBetween(left, right int) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.NotBetween(left, right)
		}
		return a.q.Area.Pid.NotBetween(left, right)
	}
}

func ConditionLevel(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Eq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).Level.Eq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).Level.In(v...)
		}
		if length == 0 {
			return a.q.Area.Level.Eq(0)
		}
		if length == 1 {
			return a.q.Area.Level.Eq(v[0])
		}
		return a.q.Area.Level.In(v...)
	}
}

func ConditionLevelNot(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		length := len(v)
		if a.newTableName != nil {
			if length == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Neq(0)
			}
			if length == 1 {
				return a.q.Area.Table(*a.newTableName).Level.Neq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).Level.NotIn(v...)
		}
		if length == 0 {
			return a.q.Area.Level.Neq(0)
		}
		if length == 1 {
			return a.q.Area.Level.Neq(v[0])
		}
		return a.q.Area.Level.NotIn(v...)
	}
}

func ConditionLevelGt(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Gt(0)
			}
			return a.q.Area.Table(*a.newTableName).Level.Gt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Level.Gt(0)
		}
		return a.q.Area.Level.Gt(v[0])
	}
}

func ConditionLevelGte(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Gte(0)
			}
			return a.q.Area.Table(*a.newTableName).Level.Gte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Level.Gte(0)
		}
		return a.q.Area.Level.Gte(v[0])
	}
}

func ConditionLevelLt(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Lt(0)
			}
			return a.q.Area.Table(*a.newTableName).Level.Lt(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Level.Lt(0)
		}
		return a.q.Area.Level.Lt(v[0])
	}
}

func ConditionLevelLte(v ...int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) == 0 {
				return a.q.Area.Table(*a.newTableName).Level.Lte(0)
			}
			return a.q.Area.Table(*a.newTableName).Level.Lte(v[0])
		}
		if len(v) == 0 {
			return a.q.Area.Level.Lte(0)
		}
		return a.q.Area.Level.Lte(v[0])
	}
}

func ConditionLevelBetween(left, right int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Between(left, right)
		}
		return a.q.Area.Level.Between(left, right)
	}
}

func ConditionLevelNotBetween(left, right int8) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.NotBetween(left, right)
		}
		return a.q.Area.Level.NotBetween(left, right)
	}
}

func ConditionCreatedAt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Eq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Eq(v[0])
		}
		return a.q.Area.CreatedAt.Eq(time.Now())
	}
}

func ConditionCreatedAtNeq(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Neq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Neq(v[0])
		}
		return a.q.Area.CreatedAt.Neq(time.Now())
	}
}

func ConditionCreatedAtGt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Gt(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Gt(v[0])
		}
		return a.q.Area.CreatedAt.Gt(time.Now())
	}
}

func ConditionCreatedAtGte(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Gte(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Gte(v[0])
		}
		return a.q.Area.CreatedAt.Gte(time.Now())
	}
}

func ConditionCreatedAtLt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Lt(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Lt(v[0])
		}
		return a.q.Area.CreatedAt.Lt(time.Now())
	}
}

func ConditionCreatedAtLte(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).CreatedAt.Lte(v[0])
			}
			return a.q.Area.Table(*a.newTableName).CreatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.CreatedAt.Lte(v[0])
		}
		return a.q.Area.CreatedAt.Lte(time.Now())
	}
}

func ConditionCreatedAtBetween(left, right time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).CreatedAt.Between(left, right)
		}
		return a.q.Area.CreatedAt.Between(left, right)
	}
}

func ConditionCreatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).CreatedAt.NotBetween(left, right)
		}
		return a.q.Area.CreatedAt.NotBetween(left, right)
	}
}

func ConditionUpdatedAt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Eq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Eq(v[0])
		}
		return a.q.Area.UpdatedAt.Eq(time.Now())
	}
}

func ConditionUpdatedAtNeq(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Neq(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Neq(v[0])
		}
		return a.q.Area.UpdatedAt.Neq(time.Now())
	}
}

func ConditionUpdatedAtGt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Gt(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Gt(v[0])
		}
		return a.q.Area.UpdatedAt.Gt(time.Now())
	}
}

func ConditionUpdatedAtGte(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Gte(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Gte(v[0])
		}
		return a.q.Area.UpdatedAt.Gte(time.Now())
	}
}

func ConditionUpdatedAtLt(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Lt(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Lt(v[0])
		}
		return a.q.Area.UpdatedAt.Lt(time.Now())
	}
}

func ConditionUpdatedAtLte(v ...time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return a.q.Area.Table(*a.newTableName).UpdatedAt.Lte(v[0])
			}
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return a.q.Area.UpdatedAt.Lte(v[0])
		}
		return a.q.Area.UpdatedAt.Lte(time.Now())
	}
}

func ConditionUpdatedAtBetween(left, right time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Between(left, right)
		}
		return a.q.Area.UpdatedAt.Between(left, right)
	}
}

func ConditionUpdatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).UpdatedAt.NotBetween(left, right)
		}
		return a.q.Area.UpdatedAt.NotBetween(left, right)
	}
}

func ConditionDeletedAtIsZero() ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return f.NewDecimal(a.q.Area.DeletedAt, f.WithTableName(*a.newTableName)).Eq(decimal.Zero)
		}
		return f.NewDecimal(a.q.Area.DeletedAt).Eq(decimal.Zero)
	}
}

func ConditionDeletedAtGtZero() ConditionOption {
	return func(a *Area) gen.Condition {
		if a.newTableName != nil {
			return f.NewDecimal(a.q.Area.DeletedAt, f.WithTableName(*a.newTableName)).Gt(decimal.Zero)
		}
		return f.NewDecimal(a.q.Area.DeletedAt).Gt(decimal.Zero)
	}
}

// UpdateOption 数据更新选项
type UpdateOption func(*Area) field.AssignExpr

// Update 自定义数据更新
func Update(update field.AssignExpr) UpdateOption {
	return func(*Area) field.AssignExpr {
		return update
	}
}

func UpdateName(v string) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Name.Value(v)
		}
		return a.q.Area.Name.Value(v)
	}
}

func UpdatePid(v int) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Value(v)
		}
		return a.q.Area.Pid.Value(v)
	}
}

// UpdatePidAdd +=
func UpdatePidAdd(v ...int) UpdateOption {
	return func(a *Area) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Add(_v)
		}
		return a.q.Area.Pid.Add(_v)
	}
}

// UpdatePidSub -=
func UpdatePidSub(v ...int) UpdateOption {
	return func(a *Area) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Sub(_v)
		}
		return a.q.Area.Pid.Sub(_v)
	}
}

// UpdatePidMul *=
func UpdatePidMul(v int) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Mul(v)
		}
		return a.q.Area.Pid.Mul(v)
	}
}

// UpdatePidDiv /=
func UpdatePidDiv(v int) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Pid.Div(v)
		}
		return a.q.Area.Pid.Div(v)
	}
}

func UpdateLevel(v int8) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Value(v)
		}
		return a.q.Area.Level.Value(v)
	}
}

// UpdateLevelAdd +=
func UpdateLevelAdd(v ...int8) UpdateOption {
	return func(a *Area) field.AssignExpr {
		_v := int8(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Add(_v)
		}
		return a.q.Area.Level.Add(_v)
	}
}

// UpdateLevelSub -=
func UpdateLevelSub(v ...int8) UpdateOption {
	return func(a *Area) field.AssignExpr {
		_v := int8(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Sub(_v)
		}
		return a.q.Area.Level.Sub(_v)
	}
}

// UpdateLevelMul *=
func UpdateLevelMul(v int8) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Mul(v)
		}
		return a.q.Area.Level.Mul(v)
	}
}

// UpdateLevelDiv /=
func UpdateLevelDiv(v int8) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).Level.Div(v)
		}
		return a.q.Area.Level.Div(v)
	}
}

func UpdateCreatedAt(v time.Time) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).CreatedAt.Value(v)
		}
		return a.q.Area.CreatedAt.Value(v)
	}
}

func UpdateUpdatedAt(v time.Time) UpdateOption {
	return func(a *Area) field.AssignExpr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Value(v)
		}
		return a.q.Area.UpdatedAt.Value(v)
	}
}

// OrderOption 数据排序选项
type OrderOption func(*Area) field.Expr

// Order 自定义数据排序
func OrderBy(order field.Expr) OrderOption {
	return func(*Area) field.Expr {
		return order
	}
}

func OrderIDAsc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).ID.Asc()
		}
		return a.q.Area.ID.Asc()
	}
}

func OrderIDDesc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).ID.Desc()
		}
		return a.q.Area.ID.Desc()
	}
}

func OrderCreatedAtAsc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).CreatedAt.Asc()
		}
		return a.q.Area.CreatedAt.Asc()
	}
}

func OrderCreatedAtDesc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).CreatedAt.Desc()
		}
		return a.q.Area.CreatedAt.Desc()
	}
}

func OrderUpdatedAtAsc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Asc()
		}
		return a.q.Area.UpdatedAt.Asc()
	}
}

func OrderUpdatedAtDesc() OrderOption {
	return func(a *Area) field.Expr {
		if a.newTableName != nil {
			return a.q.Area.Table(*a.newTableName).UpdatedAt.Desc()
		}
		return a.q.Area.UpdatedAt.Desc()
	}
}

// RelationOption 关联模型预加载选项
type RelationOption func(*Area) field.RelationField

// Relation 自定义关联模型预加载
func Relation(relation field.RelationField) RelationOption {
	return func(*Area) field.RelationField {
		return relation
	}
}

func RelationAll() RelationOption {
	return func(*Area) field.RelationField {
		return field.Associations
	}
}
