// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package userLanguage

import (
	"time"

	f "github.com/gorm-gen/field"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"

	"example/internal/global"

	"example/internal/query"

	"example/internal/repositories"
)

// UserLanguage 仓库/Repository
type UserLanguage struct {
	q            *query.Query
	db           *gorm.DB
	logger       *zap.Logger
	newTableName *string
	unscoped     bool
}

// Option UserLanguage仓库初始化选项
type Option func(*UserLanguage)

func WithQuery(q *query.Query) Option {
	return func(u *UserLanguage) {
		u.q = q
	}
}

func WithLogger(logger *zap.Logger) Option {
	return func(u *UserLanguage) {
		u.logger = logger
	}
}

func WithDB(db *gorm.DB) Option {
	return func(u *UserLanguage) {
		u.db = db
	}
}

func WithNewTableName(newTableName string) Option {
	return func(u *UserLanguage) {
		u.newTableName = &newTableName
	}
}

func WithUnscoped(unscoped ...bool) Option {
	_unscoped := true
	if len(unscoped) > 0 {
		_unscoped = unscoped[0]
	}
	return func(u *UserLanguage) {
		u.unscoped = _unscoped
	}
}

// New UserLanguage仓库初始化
func New(opts ...Option) *UserLanguage {
	u := &UserLanguage{
		q:      repositories.GetQuery(),
		db:     global.DB,
		logger: global.Logger,
	}
	for _, opt := range opts {
		opt(u)
	}
	return u
}

// ConditionOption 字段条件筛选选项
type ConditionOption func(*UserLanguage) gen.Condition

// Condition 自定义字段条件筛选
func Condition(condition gen.Condition) ConditionOption {
	return func(*UserLanguage) gen.Condition {
		return condition
	}
}

func ConditionID(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Eq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Eq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.In(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.ID.Eq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.ID.Eq(v[0])
		}
		return u.q.UserLanguage.ID.In(v...)
	}
}

func ConditionIDNot(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Neq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Neq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.NotIn(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.ID.Neq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.ID.Neq(v[0])
		}
		return u.q.UserLanguage.ID.NotIn(v...)
	}
}

func ConditionIDGt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Gt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.Gt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.ID.Gt(0)
		}
		return u.q.UserLanguage.ID.Gt(v[0])
	}
}

func ConditionIDGte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Gte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.Gte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.ID.Gte(0)
		}
		return u.q.UserLanguage.ID.Gte(v[0])
	}
}

func ConditionIDLt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Lt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.Lt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.ID.Lt(0)
		}
		return u.q.UserLanguage.ID.Lt(v[0])
	}
}

func ConditionIDLte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).ID.Lte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).ID.Lte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.ID.Lte(0)
		}
		return u.q.UserLanguage.ID.Lte(v[0])
	}
}

func ConditionIDBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).ID.Between(left, right)
		}
		return u.q.UserLanguage.ID.Between(left, right)
	}
}

func ConditionIDNotBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).ID.NotBetween(left, right)
		}
		return u.q.UserLanguage.ID.NotBetween(left, right)
	}
}

func ConditionUserID(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Eq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Eq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.In(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.UserID.Eq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.UserID.Eq(v[0])
		}
		return u.q.UserLanguage.UserID.In(v...)
	}
}

func ConditionUserIDNot(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Neq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Neq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.NotIn(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.UserID.Neq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.UserID.Neq(v[0])
		}
		return u.q.UserLanguage.UserID.NotIn(v...)
	}
}

func ConditionUserIDGt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Gt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Gt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.UserID.Gt(0)
		}
		return u.q.UserLanguage.UserID.Gt(v[0])
	}
}

func ConditionUserIDGte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Gte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Gte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.UserID.Gte(0)
		}
		return u.q.UserLanguage.UserID.Gte(v[0])
	}
}

func ConditionUserIDLt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Lt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Lt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.UserID.Lt(0)
		}
		return u.q.UserLanguage.UserID.Lt(v[0])
	}
}

func ConditionUserIDLte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).UserID.Lte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Lte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.UserID.Lte(0)
		}
		return u.q.UserLanguage.UserID.Lte(v[0])
	}
}

func ConditionUserIDBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Between(left, right)
		}
		return u.q.UserLanguage.UserID.Between(left, right)
	}
}

func ConditionUserIDNotBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.NotBetween(left, right)
		}
		return u.q.UserLanguage.UserID.NotBetween(left, right)
	}
}

func ConditionLanguageID(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Eq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Eq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.In(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.LanguageID.Eq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.LanguageID.Eq(v[0])
		}
		return u.q.UserLanguage.LanguageID.In(v...)
	}
}

func ConditionLanguageIDNot(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		length := len(v)
		if u.newTableName != nil {
			if length == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Neq(0)
			}
			if length == 1 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Neq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.NotIn(v...)
		}
		if length == 0 {
			return u.q.UserLanguage.LanguageID.Neq(0)
		}
		if length == 1 {
			return u.q.UserLanguage.LanguageID.Neq(v[0])
		}
		return u.q.UserLanguage.LanguageID.NotIn(v...)
	}
}

func ConditionLanguageIDGt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Gt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Gt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.LanguageID.Gt(0)
		}
		return u.q.UserLanguage.LanguageID.Gt(v[0])
	}
}

func ConditionLanguageIDGte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Gte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Gte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.LanguageID.Gte(0)
		}
		return u.q.UserLanguage.LanguageID.Gte(v[0])
	}
}

func ConditionLanguageIDLt(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Lt(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Lt(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.LanguageID.Lt(0)
		}
		return u.q.UserLanguage.LanguageID.Lt(v[0])
	}
}

func ConditionLanguageIDLte(v ...int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) == 0 {
				return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Lte(0)
			}
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Lte(v[0])
		}
		if len(v) == 0 {
			return u.q.UserLanguage.LanguageID.Lte(0)
		}
		return u.q.UserLanguage.LanguageID.Lte(v[0])
	}
}

func ConditionLanguageIDBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Between(left, right)
		}
		return u.q.UserLanguage.LanguageID.Between(left, right)
	}
}

func ConditionLanguageIDNotBetween(left, right int) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.NotBetween(left, right)
		}
		return u.q.UserLanguage.LanguageID.NotBetween(left, right)
	}
}

func ConditionCreatedAt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Eq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Eq(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Eq(time.Now())
	}
}

func ConditionCreatedAtNeq(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Neq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Neq(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Neq(time.Now())
	}
}

func ConditionCreatedAtGt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Gt(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Gt(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Gt(time.Now())
	}
}

func ConditionCreatedAtGte(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Gte(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Gte(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Gte(time.Now())
	}
}

func ConditionCreatedAtLt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Lt(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Lt(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Lt(time.Now())
	}
}

func ConditionCreatedAtLte(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Lte(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.CreatedAt.Lte(v[0])
		}
		return u.q.UserLanguage.CreatedAt.Lte(time.Now())
	}
}

func ConditionCreatedAtBetween(left, right time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Between(left, right)
		}
		return u.q.UserLanguage.CreatedAt.Between(left, right)
	}
}

func ConditionCreatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.NotBetween(left, right)
		}
		return u.q.UserLanguage.CreatedAt.NotBetween(left, right)
	}
}

func ConditionUpdatedAt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Eq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Eq(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Eq(time.Now())
	}
}

func ConditionUpdatedAtNeq(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Neq(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Neq(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Neq(time.Now())
	}
}

func ConditionUpdatedAtGt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Gt(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Gt(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Gt(time.Now())
	}
}

func ConditionUpdatedAtGte(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Gte(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Gte(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Gte(time.Now())
	}
}

func ConditionUpdatedAtLt(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Lt(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Lt(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Lt(time.Now())
	}
}

func ConditionUpdatedAtLte(v ...time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Lte(v[0])
			}
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return u.q.UserLanguage.UpdatedAt.Lte(v[0])
		}
		return u.q.UserLanguage.UpdatedAt.Lte(time.Now())
	}
}

func ConditionUpdatedAtBetween(left, right time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Between(left, right)
		}
		return u.q.UserLanguage.UpdatedAt.Between(left, right)
	}
}

func ConditionUpdatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.NotBetween(left, right)
		}
		return u.q.UserLanguage.UpdatedAt.NotBetween(left, right)
	}
}

func ConditionDeletedAtIsZero() ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return f.NewDecimal(u.q.UserLanguage.DeletedAt, f.WithTableName(*u.newTableName)).Eq(decimal.Zero)
		}
		return f.NewDecimal(u.q.UserLanguage.DeletedAt).Eq(decimal.Zero)
	}
}

func ConditionDeletedAtGtZero() ConditionOption {
	return func(u *UserLanguage) gen.Condition {
		if u.newTableName != nil {
			return f.NewDecimal(u.q.UserLanguage.DeletedAt, f.WithTableName(*u.newTableName)).Gt(decimal.Zero)
		}
		return f.NewDecimal(u.q.UserLanguage.DeletedAt).Gt(decimal.Zero)
	}
}

// UpdateOption 数据更新选项
type UpdateOption func(*UserLanguage) field.AssignExpr

// Update 自定义数据更新
func Update(update field.AssignExpr) UpdateOption {
	return func(*UserLanguage) field.AssignExpr {
		return update
	}
}

func UpdateUserID(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Value(v)
		}
		return u.q.UserLanguage.UserID.Value(v)
	}
}

// UpdateUserIDAdd +=
func UpdateUserIDAdd(v ...int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Add(_v)
		}
		return u.q.UserLanguage.UserID.Add(_v)
	}
}

// UpdateUserIDSub -=
func UpdateUserIDSub(v ...int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Sub(_v)
		}
		return u.q.UserLanguage.UserID.Sub(_v)
	}
}

// UpdateUserIDMul *=
func UpdateUserIDMul(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Mul(v)
		}
		return u.q.UserLanguage.UserID.Mul(v)
	}
}

// UpdateUserIDDiv /=
func UpdateUserIDDiv(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UserID.Div(v)
		}
		return u.q.UserLanguage.UserID.Div(v)
	}
}

func UpdateLanguageID(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Value(v)
		}
		return u.q.UserLanguage.LanguageID.Value(v)
	}
}

// UpdateLanguageIDAdd +=
func UpdateLanguageIDAdd(v ...int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Add(_v)
		}
		return u.q.UserLanguage.LanguageID.Add(_v)
	}
}

// UpdateLanguageIDSub -=
func UpdateLanguageIDSub(v ...int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Sub(_v)
		}
		return u.q.UserLanguage.LanguageID.Sub(_v)
	}
}

// UpdateLanguageIDMul *=
func UpdateLanguageIDMul(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Mul(v)
		}
		return u.q.UserLanguage.LanguageID.Mul(v)
	}
}

// UpdateLanguageIDDiv /=
func UpdateLanguageIDDiv(v int) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).LanguageID.Div(v)
		}
		return u.q.UserLanguage.LanguageID.Div(v)
	}
}

func UpdateCreatedAt(v time.Time) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Value(v)
		}
		return u.q.UserLanguage.CreatedAt.Value(v)
	}
}

func UpdateUpdatedAt(v time.Time) UpdateOption {
	return func(u *UserLanguage) field.AssignExpr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Value(v)
		}
		return u.q.UserLanguage.UpdatedAt.Value(v)
	}
}

// OrderOption 数据排序选项
type OrderOption func(*UserLanguage) field.Expr

// Order 自定义数据排序
func OrderBy(order field.Expr) OrderOption {
	return func(*UserLanguage) field.Expr {
		return order
	}
}

func OrderIDAsc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).ID.Asc()
		}
		return u.q.UserLanguage.ID.Asc()
	}
}

func OrderIDDesc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).ID.Desc()
		}
		return u.q.UserLanguage.ID.Desc()
	}
}

func OrderCreatedAtAsc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Asc()
		}
		return u.q.UserLanguage.CreatedAt.Asc()
	}
}

func OrderCreatedAtDesc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).CreatedAt.Desc()
		}
		return u.q.UserLanguage.CreatedAt.Desc()
	}
}

func OrderUpdatedAtAsc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Asc()
		}
		return u.q.UserLanguage.UpdatedAt.Asc()
	}
}

func OrderUpdatedAtDesc() OrderOption {
	return func(u *UserLanguage) field.Expr {
		if u.newTableName != nil {
			return u.q.UserLanguage.Table(*u.newTableName).UpdatedAt.Desc()
		}
		return u.q.UserLanguage.UpdatedAt.Desc()
	}
}

// RelationOption 关联模型预加载选项
type RelationOption func(*UserLanguage) field.RelationField

// Relation 自定义关联模型预加载
func Relation(relation field.RelationField) RelationOption {
	return func(*UserLanguage) field.RelationField {
		return relation
	}
}

func RelationAll() RelationOption {
	return func(*UserLanguage) field.RelationField {
		return field.Associations
	}
}
