// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/repository. DO NOT EDIT.

package classify

import (
	"strings"
	"time"

	f "github.com/gorm-gen/plugin/field"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"

	"example/internal/global"

	"example/internal/query"

	"example/internal/repositories"
)

// Classify 仓库/Repository
type Classify struct {
	q            *query.Query
	db           *gorm.DB
	logger       *zap.Logger
	unscoped     bool
	newTableName *string
}

// Option Classify仓库初始化选项
type Option func(*Classify)

func WithQuery(q *query.Query) Option {
	return func(c *Classify) {
		c.q = q
	}
}

func WithLogger(logger *zap.Logger) Option {
	return func(c *Classify) {
		c.logger = logger
	}
}

func WithDB(db *gorm.DB) Option {
	return func(c *Classify) {
		c.db = db
	}
}

func WithNewTableName(newTableName string) Option {
	return func(c *Classify) {
		c.newTableName = &newTableName
	}
}

func WithUnscoped() Option {
	return func(c *Classify) {
		c.unscoped = true
	}
}

// New Classify仓库初始化
func New(opts ...Option) *Classify {
	c := &Classify{
		q:      repositories.GetQuery(),
		db:     global.DB,
		logger: global.Logger,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// ConditionOption 字段条件筛选选项
type ConditionOption func(*Classify) gen.Condition

// Condition 自定义字段条件筛选
func Condition(condition gen.Condition) ConditionOption {
	return func(*Classify) gen.Condition {
		return condition
	}
}

func ConditionID(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Eq(0)
			}
			if length == 1 {
				return c.q.Classify.Table(*c.newTableName).ID.Eq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).ID.In(v...)
		}
		if length == 0 {
			return c.q.Classify.ID.Eq(0)
		}
		if length == 1 {
			return c.q.Classify.ID.Eq(v[0])
		}
		return c.q.Classify.ID.In(v...)
	}
}

func ConditionIDNot(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Neq(0)
			}
			if length == 1 {
				return c.q.Classify.Table(*c.newTableName).ID.Neq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).ID.NotIn(v...)
		}
		if length == 0 {
			return c.q.Classify.ID.Neq(0)
		}
		if length == 1 {
			return c.q.Classify.ID.Neq(v[0])
		}
		return c.q.Classify.ID.NotIn(v...)
	}
}

func ConditionIDGt(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Gt(0)
			}
			return c.q.Classify.Table(*c.newTableName).ID.Gt(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.ID.Gt(0)
		}
		return c.q.Classify.ID.Gt(v[0])
	}
}

func ConditionIDGte(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Gte(0)
			}
			return c.q.Classify.Table(*c.newTableName).ID.Gte(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.ID.Gte(0)
		}
		return c.q.Classify.ID.Gte(v[0])
	}
}

func ConditionIDLt(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Lt(0)
			}
			return c.q.Classify.Table(*c.newTableName).ID.Lt(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.ID.Lt(0)
		}
		return c.q.Classify.ID.Lt(v[0])
	}
}

func ConditionIDLte(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).ID.Lte(0)
			}
			return c.q.Classify.Table(*c.newTableName).ID.Lte(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.ID.Lte(0)
		}
		return c.q.Classify.ID.Lte(v[0])
	}
}

func ConditionIDBetween(left, right int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).ID.Between(left, right)
		}
		return c.q.Classify.ID.Between(left, right)
	}
}

func ConditionIDNotBetween(left, right int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).ID.NotBetween(left, right)
		}
		return c.q.Classify.ID.NotBetween(left, right)
	}
}

func ConditionName(v ...string) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).Name.Eq("")
			}
			return c.q.Classify.Table(*c.newTableName).Name.Eq(v[0])
		}
		if length == 0 {
			return c.q.Classify.Name.Eq("")
		}
		return c.q.Classify.Name.Eq(v[0])
	}
}

func ConditionNameNeq(v ...string) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).Name.Neq("")
			}
			return c.q.Classify.Table(*c.newTableName).Name.Neq(v[0])
		}
		if length == 0 {
			return c.q.Classify.Name.Neq("")
		}
		return c.q.Classify.Name.Neq(v[0])
	}
}

func ConditionNameLike(v string) ConditionOption {
	return func(c *Classify) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Name.Like(v)
		}
		return c.q.Classify.Name.Like(v)
	}
}

func ConditionNameNotLike(v string) ConditionOption {
	return func(c *Classify) gen.Condition {
		if !strings.Contains(v, "%") {
			v = "%" + v + "%"
		}
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Name.NotLike(v)
		}
		return c.q.Classify.Name.NotLike(v)
	}
}

func ConditionPid(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Eq(0)
			}
			if length == 1 {
				return c.q.Classify.Table(*c.newTableName).Pid.Eq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).Pid.In(v...)
		}
		if length == 0 {
			return c.q.Classify.Pid.Eq(0)
		}
		if length == 1 {
			return c.q.Classify.Pid.Eq(v[0])
		}
		return c.q.Classify.Pid.In(v...)
	}
}

func ConditionPidNot(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		length := len(v)
		if c.newTableName != nil {
			if length == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Neq(0)
			}
			if length == 1 {
				return c.q.Classify.Table(*c.newTableName).Pid.Neq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).Pid.NotIn(v...)
		}
		if length == 0 {
			return c.q.Classify.Pid.Neq(0)
		}
		if length == 1 {
			return c.q.Classify.Pid.Neq(v[0])
		}
		return c.q.Classify.Pid.NotIn(v...)
	}
}

func ConditionPidGt(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Gt(0)
			}
			return c.q.Classify.Table(*c.newTableName).Pid.Gt(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.Pid.Gt(0)
		}
		return c.q.Classify.Pid.Gt(v[0])
	}
}

func ConditionPidGte(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Gte(0)
			}
			return c.q.Classify.Table(*c.newTableName).Pid.Gte(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.Pid.Gte(0)
		}
		return c.q.Classify.Pid.Gte(v[0])
	}
}

func ConditionPidLt(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Lt(0)
			}
			return c.q.Classify.Table(*c.newTableName).Pid.Lt(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.Pid.Lt(0)
		}
		return c.q.Classify.Pid.Lt(v[0])
	}
}

func ConditionPidLte(v ...int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) == 0 {
				return c.q.Classify.Table(*c.newTableName).Pid.Lte(0)
			}
			return c.q.Classify.Table(*c.newTableName).Pid.Lte(v[0])
		}
		if len(v) == 0 {
			return c.q.Classify.Pid.Lte(0)
		}
		return c.q.Classify.Pid.Lte(v[0])
	}
}

func ConditionPidBetween(left, right int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Between(left, right)
		}
		return c.q.Classify.Pid.Between(left, right)
	}
}

func ConditionPidNotBetween(left, right int) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.NotBetween(left, right)
		}
		return c.q.Classify.Pid.NotBetween(left, right)
	}
}

func ConditionCreatedAt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Eq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Eq(v[0])
		}
		return c.q.Classify.CreatedAt.Eq(time.Now())
	}
}

func ConditionCreatedAtNeq(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Neq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Neq(v[0])
		}
		return c.q.Classify.CreatedAt.Neq(time.Now())
	}
}

func ConditionCreatedAtGt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Gt(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Gt(v[0])
		}
		return c.q.Classify.CreatedAt.Gt(time.Now())
	}
}

func ConditionCreatedAtGte(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Gte(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Gte(v[0])
		}
		return c.q.Classify.CreatedAt.Gte(time.Now())
	}
}

func ConditionCreatedAtLt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Lt(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Lt(v[0])
		}
		return c.q.Classify.CreatedAt.Lt(time.Now())
	}
}

func ConditionCreatedAtLte(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).CreatedAt.Lte(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.CreatedAt.Lte(v[0])
		}
		return c.q.Classify.CreatedAt.Lte(time.Now())
	}
}

func ConditionCreatedAtBetween(left, right time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Between(left, right)
		}
		return c.q.Classify.CreatedAt.Between(left, right)
	}
}

func ConditionCreatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).CreatedAt.NotBetween(left, right)
		}
		return c.q.Classify.CreatedAt.NotBetween(left, right)
	}
}

func ConditionUpdatedAt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Eq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Eq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Eq(v[0])
		}
		return c.q.Classify.UpdatedAt.Eq(time.Now())
	}
}

func ConditionUpdatedAtNeq(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Neq(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Neq(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Neq(v[0])
		}
		return c.q.Classify.UpdatedAt.Neq(time.Now())
	}
}

func ConditionUpdatedAtGt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Gt(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Gt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Gt(v[0])
		}
		return c.q.Classify.UpdatedAt.Gt(time.Now())
	}
}

func ConditionUpdatedAtGte(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Gte(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Gte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Gte(v[0])
		}
		return c.q.Classify.UpdatedAt.Gte(time.Now())
	}
}

func ConditionUpdatedAtLt(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Lt(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Lt(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Lt(v[0])
		}
		return c.q.Classify.UpdatedAt.Lt(time.Now())
	}
}

func ConditionUpdatedAtLte(v ...time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			if len(v) > 0 && !v[0].IsZero() {
				return c.q.Classify.Table(*c.newTableName).UpdatedAt.Lte(v[0])
			}
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Lte(time.Now())
		}
		if len(v) > 0 && !v[0].IsZero() {
			return c.q.Classify.UpdatedAt.Lte(v[0])
		}
		return c.q.Classify.UpdatedAt.Lte(time.Now())
	}
}

func ConditionUpdatedAtBetween(left, right time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Between(left, right)
		}
		return c.q.Classify.UpdatedAt.Between(left, right)
	}
}

func ConditionUpdatedAtNotBetween(left, right time.Time) ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.NotBetween(left, right)
		}
		return c.q.Classify.UpdatedAt.NotBetween(left, right)
	}
}

func ConditionDeletedAtIsZero() ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return f.NewDecimal(c.q.Classify.DeletedAt, f.WithTableName(*c.newTableName)).Eq(decimal.Zero)
		}
		return f.NewDecimal(c.q.Classify.DeletedAt).Eq(decimal.Zero)
	}
}

func ConditionDeletedAtGtZero() ConditionOption {
	return func(c *Classify) gen.Condition {
		if c.newTableName != nil {
			return f.NewDecimal(c.q.Classify.DeletedAt, f.WithTableName(*c.newTableName)).Gt(decimal.Zero)
		}
		return f.NewDecimal(c.q.Classify.DeletedAt).Gt(decimal.Zero)
	}
}

// UpdateOption 数据更新选项
type UpdateOption func(*Classify) field.AssignExpr

// Update 自定义数据更新
func Update(update field.AssignExpr) UpdateOption {
	return func(*Classify) field.AssignExpr {
		return update
	}
}

func UpdateName(v string) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Name.Value(v)
		}
		return c.q.Classify.Name.Value(v)
	}
}

func UpdatePid(v int) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Value(v)
		}
		return c.q.Classify.Pid.Value(v)
	}
}

// UpdatePidAdd +=
func UpdatePidAdd(v ...int) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Add(_v)
		}
		return c.q.Classify.Pid.Add(_v)
	}
}

// UpdatePidSub -=
func UpdatePidSub(v ...int) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		_v := int(1)
		if len(v) > 0 {
			_v = v[0]
		}
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Sub(_v)
		}
		return c.q.Classify.Pid.Sub(_v)
	}
}

// UpdatePidMul *=
func UpdatePidMul(v int) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Mul(v)
		}
		return c.q.Classify.Pid.Mul(v)
	}
}

// UpdatePidDiv /=
func UpdatePidDiv(v int) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).Pid.Div(v)
		}
		return c.q.Classify.Pid.Div(v)
	}
}

func UpdateCreatedAt(v time.Time) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Value(v)
		}
		return c.q.Classify.CreatedAt.Value(v)
	}
}

func UpdateUpdatedAt(v time.Time) UpdateOption {
	return func(c *Classify) field.AssignExpr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Value(v)
		}
		return c.q.Classify.UpdatedAt.Value(v)
	}
}

// OrderOption 数据排序选项
type OrderOption func(*Classify) field.Expr

// Order 自定义数据排序
func OrderBy(order field.Expr) OrderOption {
	return func(*Classify) field.Expr {
		return order
	}
}

func OrderIDAsc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).ID.Asc()
		}
		return c.q.Classify.ID.Asc()
	}
}

func OrderIDDesc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).ID.Desc()
		}
		return c.q.Classify.ID.Desc()
	}
}

func OrderCreatedAtAsc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Asc()
		}
		return c.q.Classify.CreatedAt.Asc()
	}
}

func OrderCreatedAtDesc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).CreatedAt.Desc()
		}
		return c.q.Classify.CreatedAt.Desc()
	}
}

func OrderUpdatedAtAsc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Asc()
		}
		return c.q.Classify.UpdatedAt.Asc()
	}
}

func OrderUpdatedAtDesc() OrderOption {
	return func(c *Classify) field.Expr {
		if c.newTableName != nil {
			return c.q.Classify.Table(*c.newTableName).UpdatedAt.Desc()
		}
		return c.q.Classify.UpdatedAt.Desc()
	}
}

// RelationOption 关联模型预加载选项
type RelationOption func(*Classify) field.RelationField

// Relation 自定义关联模型预加载
func Relation(relation field.RelationField) RelationOption {
	return func(*Classify) field.RelationField {
		return relation
	}
}

func RelationAll() RelationOption {
	return func(*Classify) field.RelationField {
		return field.Associations
	}
}
