// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package orderItem

import (
	"context"

	"go.uber.org/zap"

	"example/internal/query"

    "example/internal/repositories"

    "example/internal/models"
)

type create struct {
	core      *OrderItem
	tx        *query.Query
	qTx       *query.QueryTx
	unscoped  bool
	values    []*models.OrderItem
	batchSize int
}

// Create 添加数据
func (o *OrderItem) Create() *create {
	return &create{
		core:     o,
		unscoped: o.unscoped,
		values:   make([]*models.OrderItem, 0),
	}
}

// Tx 设置为事务
func (c *create) Tx(tx *query.Query) *create {
	c.tx = tx
	if tx != nil {
		c.qTx = nil
	}
	return c
}

// QueryTx 设置为手动事务
func (c *create) QueryTx(tx *query.QueryTx) *create {
	c.qTx = tx
	if tx != nil {
		c.tx = nil
	}
	return c
}

func (c *create) Unscoped() *create {
	c.unscoped = true
	return c
}

func (c *create) Values(values ...*models.OrderItem) *create {
	c.values = append(c.values, values...)
	return c
}

// BatchSize 当批量插入时指定创建的数量
func (c *create) BatchSize(batchSize uint) *create {
	c.batchSize = int(batchSize)
	return c
}

// Do 执行添加数据
func (c *create) Do(ctx context.Context) (err error) {
	length := len(c.values)
	if length == 0 {
		return nil
	}
	cq := c.core.q.OrderItem
	if c.tx != nil {
		cq = c.tx.OrderItem
	}
	if c.qTx != nil {
		cq = c.qTx.OrderItem
	}
	cr := cq.WithContext(ctx)
	if c.core.newTableName != nil && *c.core.newTableName != "" {
		cr = cq.Table(*c.core.newTableName).WithContext(ctx)
	}
	if c.unscoped {
		cr = cr.Unscoped()
	}
	if length > 1 && c.batchSize > 0 {
		err = cr.CreateInBatches(c.values, c.batchSize)
	} else {
		err = cr.Create(c.values...)
	}
	if err != nil {
		if repositories.IsRealErr(err) {
			c.core.logger.Error("【OrderItem.Create】失败", zap.Error(err))
		}
		return err
	}
	return nil
}
