// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package orderItem

import (
	"context"

	"go.uber.org/zap"
    "gorm.io/gen"

	"example/internal/query"

	"example/internal/repositories"
)

type _delete struct {
	core          *OrderItem
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
}

// Delete 删除数据
func (o *OrderItem) Delete() *_delete {
	return &_delete{
		core:          o,
		unscoped:      o.unscoped,
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (d *_delete) Tx(tx *query.Query) *_delete {
	d.tx = tx
	if tx != nil {
		d.qTx = nil
	}
	return d
}

// QueryTx 设置为手动事务
func (d *_delete) QueryTx(tx *query.QueryTx) *_delete {
	d.qTx = tx
	if tx != nil {
		d.tx = nil
	}
	return d
}

func (d *_delete) Unscoped() *_delete {
	d.unscoped = true
	return d
}

func (d *_delete) Where(opts ...ConditionOption) *_delete {
	d.conditionOpts = append(d.conditionOpts, opts...)
	return d
}

// Do 执行删除数据
func (d *_delete) Do(ctx context.Context) (int64, error) {
	dq := d.core.q.OrderItem
	if d.tx != nil {
		dq = d.tx.OrderItem
	}
	if d.qTx != nil {
		dq = d.qTx.OrderItem
	}
	dr := dq.WithContext(ctx)
	if d.core.newTableName != nil && *d.core.newTableName != "" {
		dr = dq.Table(*d.core.newTableName).WithContext(ctx)
	}
	if d.unscoped {
		dr = dr.Unscoped()
	}
	if len(d.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(d.conditionOpts))
		for _, opt := range d.conditionOpts {
			conditions = append(conditions, opt(d.core))
		}
		if len(conditions) > 0 {
			dr = dr.Where(conditions...)
		}
	}
	res, err := dr.Delete()
	if err != nil {
		if repositories.IsRealErr(err) {
			d.core.logger.Error("【OrderItem.Delete】失败", zap.Error(err))
		}
		return 0, err
	}
	return res.RowsAffected, nil
}
