// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package orderItem

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"

	"example/internal/query"

	"example/internal/repositories"
)

type _multiCount struct {
	core          *OrderItem
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
	sharding      []string
	worker        chan struct{}
}

// MultiCount 获取多表数据总记录
func (o *OrderItem) MultiCount(sharding []string) *_multiCount {
	return &_multiCount{
		core:          o,
		unscoped:      o.unscoped,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (c *_multiCount) Worker(worker chan struct{}) *_multiCount {
	if worker == nil {
		return c
	}
	c.worker = worker
	return c
}

// Tx 设置为事务
func (c *_multiCount) Tx(tx *query.Query) *_multiCount {
	c.tx = tx
	c.qTx = nil
	return c
}

// QueryTx 设置为手动事务
func (c *_multiCount) QueryTx(tx *query.QueryTx) *_multiCount {
	c.qTx = tx
	c.tx = nil
	return c
}

func (c *_multiCount) Unscoped() *_multiCount {
	c.unscoped = true
	return c
}

func (c *_multiCount) Where(opts ...ConditionOption) *_multiCount {
	c.conditionOpts = append(c.conditionOpts, opts...)
	return c
}

// Do 执行获取多表数据总记录
func (c *_multiCount) Do(ctx context.Context) (int64, map[string]int64, error) {
	if len(c.sharding) == 0 {
		return 0, nil, nil
	}
	cq := c.core.q.OrderItem
	if c.tx != nil {
		cq = c.tx.OrderItem
	}
	if c.qTx != nil {
		cq = c.qTx.OrderItem
	}
	var conditions []gen.Condition
	if len(c.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(c.conditionOpts))
		for _, opt := range c.conditionOpts {
			conditions = append(conditions, opt(c.core))
		}
	}
	sm := sync.Map{}
	wg := sync.WaitGroup{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range c.sharding {
		c.worker <- struct{}{}
		wg.Add(1)
		go func(sharding string) {
			defer func() {
				if r := recover(); r != nil {
					c.core.logger.Error(fmt.Sprintf("【OrderItem.MultiCount.%s】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan <- fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				<-c.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, ConditionSharding(sharding)(c.core))
			cr := cq.WithContext(ctx)
			if c.unscoped {
				cr = cr.Unscoped()
			}
			count, err := cr.Where(_conditions...).Count()
			if err != nil {
				if repositories.IsRealErr(err) {
					c.core.logger.Error(fmt.Sprintf("【OrderItem.MultiCount.%s】失败", sharding), zap.Error(err))
				}
				errChan <- err
				return
			}
			sm.Store(sharding, count)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan <- struct{}{}
	}()
	select {
	case <-endChan:
		count := int64(0)
		m := make(map[string]int64, len(c.sharding))
		sm.Range(func(key, value interface{}) bool {
			v := value.(int64)
			m[key.(string)] = v
			count += v
			return true
		})
		return count, m, nil
	case err := <-errChan:
		return 0, nil, err
	}
}
