// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package orderItem

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"example/internal/query"

    "example/internal/repositories"
)

type update struct {
	core          *OrderItem
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	updateOpts    []UpdateOption
	conditionOpts []ConditionOption
}

// Update 更新数据
func (o *OrderItem) Update() *update {
	return &update{
		core:          o,
		unscoped:      o.unscoped,
		updateOpts:    make([]UpdateOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (u *update) Tx(tx *query.Query) *update {
	u.tx = tx
	if tx != nil {
		u.qTx = nil
	}
	return u
}

// QueryTx 设置为手动事务
func (u *update) QueryTx(tx *query.QueryTx) *update {
	u.qTx = tx
	if tx != nil {
		u.tx = nil
	}
	return u
}

func (u *update) Unscoped() *update {
	u.unscoped = true
	return u
}

func (u *update) Update(opts ...UpdateOption) *update {
	u.updateOpts = append(u.updateOpts, opts...)
	return u
}

func (u *update) Where(opts ...ConditionOption) *update {
	u.conditionOpts = append(u.conditionOpts, opts...)
	return u
}

// Do 执行更新数据
func (u *update) Do(ctx context.Context) (int64, error) {
	if len(u.updateOpts) == 0 {
		return 0, nil
	}
	uq := u.core.q.OrderItem
	if u.tx != nil {
		uq = u.tx.OrderItem
	}
	if u.qTx != nil {
		uq = u.qTx.OrderItem
	}
	ur := uq.WithContext(ctx)
	if u.core.newTableName != nil && *u.core.newTableName != "" {
		ur = uq.Table(*u.core.newTableName).WithContext(ctx)
	}
	if u.unscoped {
		ur = ur.Unscoped()
	}
	if len(u.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(u.conditionOpts))
		for _, opt := range u.conditionOpts {
			conditions = append(conditions, opt(u.core))
		}
		if len(conditions) > 0 {
			ur = ur.Where(conditions...)
		}
	}
	columns := make([]field.AssignExpr, 0, len(u.updateOpts))
	for _, opt := range u.updateOpts {
		columns = append(columns, opt(u.core))
	}
	if len(columns) == 0 {
		return 0, nil
	}
	res, err := ur.UpdateSimple(columns...)
	if err != nil {
		if repositories.IsRealErr(err) {
			u.core.logger.Error("【OrderItem.Update】失败", zap.Error(err))
		}
		return 0, err
	}
	return res.RowsAffected, nil
}
